name: CI
on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]



jobs:
  lint:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: "30.0.3"

      - name: Create local.properties
        run: echo "sdk.dir=/usr/local/lib/android/sdk" > $GITHUB_WORKSPACE/local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run lint
        run: ./gradlew lintDebug

      - name: Upload html test report
        uses: actions/upload-artifact@v4
        with:
          name: index.html
          path: app/build/reports/lint-results-debug.html

  unit-test:
    needs: [ lint ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: "30.0.3"

      - name: Create local.properties
        run: echo "sdk.dir=/usr/local/lib/android/sdk" > $GITHUB_WORKSPACE/local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/


  instrumentation-test:
    needs: [ unit-test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: "30.0.3"


      - name: Create local.properties
        run: echo "sdk.dir=/usr/local/lib/android/sdk" > $GITHUB_WORKSPACE/local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Start emulator and run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          emulator-boot-timeout: 900
          disable-animations: true
          disable-linux-hw-accel: true
          script: |
            # Restart ADB server to avoid broken pipe errors
           adb kill-server
           adb start-server

          # Wait for the emulator to be ready
           adb -s emulator-5554 wait-for-device

          # Increase screen off timeout and logcat buffer size
           adb -s emulator-5554 shell settings put system screen_off_timeout 1800000
           adb -s emulator-5554 logcat -G 2M

          # Apply animation settings
           adb -s emulator-5554 shell settings put global window_animation_scale 0.0
           adb -s emulator-5554 shell settings put global transition_animation_scale 0.0
           adb -s emulator-5554 shell settings put global animator_duration_scale 0.0

          # Run the instrumentation tests
           ./gradlew connectedDebugAndroidTest

      - name: Terminate Emulator
        run: |
          # Extend wait time before killing the emulator
          export ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL=60
          adb -s emulator-5554 emu kill

      - name: Upload instrumentation test report
        uses: actions/upload-artifact@v4
        with:
          name: instrumentation_test_report
          path: app/build/reports/androidTests/connected/